name: Chris Montrois
description: Developer. Dude.

url: http://www.chrismontrois.net

markdown: rdiscount
permalink: pretty
highlighter: pygments

syntax-highlighting:
  enabled: true

sass:
  sass_dir: _scss
  style: :compressed
