name: Chris Montrois
description: Developer. Dude.

url: http://www.chrismontrois.net

markdown: rdiscount
permalink: pretty

syntax-highlighting:
  enabled: true
  css: css/syntax.css

sass:
  sass_dir: _scss
  style: :compressed
